export const ADMIN = 'ADMIN'

export const ADD_CLASSES = 'ADD_CLASSES'
export const SHOW_MODAL_ADD_CLASSES = 'SHOW_MODAL_ADD_CLASSES';
export const CLOSE_MODAL_ADD_CLASSES = 'CLOSE_MODAL_ADD_CLASSES';
export const ADD_KEY_CONTROL_CLASS_LIST = 'ADD_KEY_CONTROL_CLASS_LIST';
export const ADD_KEY_FILTER = 'ADD_KEY_FILTER';

export const SHOW_MODAL_ADD_STUDENTS = 'SHOW_MODAL_ADD_STUDENTS';
export const CLOSE_MODAL_ADD_STUDENTS = 'CLOSE_MODAL_ADD_STUDENTS';
export const ADD_STUDENTS = 'ADD_STUDENTS'

export const SHOW_MODAL_ADD_TEACHER = 'SHOW_MODAL_ADD_TEACHER';
export const CLOSE_MODAL_ADD_TEACHER = 'CLOSE_MODAL_ADD_TEACHER';

export const SHOW_DETAIL_STUDENT = 'SHOW_DETAIL_STUDENT';
export const CLOSE_DETAIL_STUDENT = 'CLOSE_DETAIL_STUDENT';
export const ADD_ID_DETAIL = 'ADD_ID_DETAIL';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
