export const API_ENDPOINT = 'http://localhost:8080';
//profile admin
export const FETCH_PROFILE_ADMIN = 'FETCH_PROFILE_ADMIN';
export const FETCH_PROFILE_ADMIN_SUCCESS = 'FETCH_PROFILE_ADMIN_SUCCESS';
export const FETCH_PROFILE_ADMIN_FAILED = 'FETCH_PROFILE_ADMIN_FAILED';

//subjects
export const FETCH_SUBJECTS = 'FETCH_SUBJECTS';
export const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS';
export const FETCH_SUBJECTS_FAILED = 'FETCH_SUBJECTS_FAILED';

//students
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS';
export const FETCH_STUDENTS_FAILED = 'FETCH_STUDENTS_FAILED';

//teachers
export const FETCH_TEACHERS = 'FETCH_TEACHERS';
export const FETCH_TEACHERS_SUCCESS = 'FETCH_TEACHERS_SUCCESS';
export const FETCH_TEACHERS_FAILED = 'FETCH_TEACHERS_FAILED';

//classes
export const FETCH_CLASSES = 'FETCH_CLASSES';
export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_FAILED = 'FETCH_CLASSES_FAILED';